"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/affiliatenetworks/:id/ → Delete a affiliate network.
- GET /:version/affiliatenetworks/:id/ → Get one affiliate network.
- GET /:version/affiliatenetworks/ → Get all affiliate networks of this webshop.
- OPTIONS /:version/affiliatenetworks/ → None
- PATCH /:version/affiliatenetworks/:id/ → Patch a affiliate network.
- POST /:version/affiliatenetworks/ → Post a affiliate network.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Affiliatenetworks(CCVApiEndpoints):
    """
    These are the affliate networks in the webshop installed by a app or by a third party.
    """

    def delete_a_affiliate_network(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a affiliate network.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/affiliatenetworks/{id}/",
        )

    def get_one_affiliate_network(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one affiliate network.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/affiliatenetworks/{id}/",
        )

    def get_all_affiliate_networks_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all affiliate networks of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/affiliatenetworks/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patch_a_affiliate_network(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a affiliate network.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/affiliatenetworks/{id}/",
            body=body,
        )

    def post_a_affiliate_network(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a affiliate network.
        """
        return self.client._post(
            uri_path="/api/rest/v1/affiliatenetworks/",
            body=body,
        )