"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/apicredentialdevicesettings/ → Retrieve all the settings for the related device based on api key.
- OPTIONS /:version/apicredentialdevicesettings/ → None
- PUT /:version/apicredentialdevicesettings/ → Overwrites all the settings related to the linked terminal device.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Apicredentialdevicesettings(CCVApiEndpoints):
    """
    Settings that are linked to a terminal device.
    """

    def retrieve_all_the_settings_for_the_related_device_based_on_api_key(
        self,
    ) -> CCVShopResult:
        """
        Retrieve all the settings for the related device based on api key.
        """
        return self.client._get(
            uri_path="/api/rest/v1/apicredentialdevicesettings/",
        )

    def overwrites_all_the_settings_related_to_the_linked_terminal_device(
        self,
    ) -> CCVShopResult:
        """
        Overwrites all the settings related to the linked terminal device.
        """
        return self.client._put(
            uri_path="/api/rest/v1/apicredentialdevicesettings/",
        )