"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/apicredentialdevices/:id/ → Get a single terminal device.
- OPTIONS /:version/apicredentialdevices/ → None
- POST /:version/apicredentialdevices/ → Store a new terminal device.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Apicredentialdevices(CCVApiEndpoints):
    """
    A terminal device that's linked to a specific API credential.
    """

    def get_a_single_terminal_device(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single terminal device.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/apicredentialdevices/{id}/",
        )

    def store_a_new_terminal_device(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Store a new terminal device.
        """
        return self.client._post(
            uri_path="/api/rest/v1/apicredentialdevices/",
            body=body,
        )