"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/appconfig/:id/ → Delete an app configuration page
- GET /:version/apps/:id/appconfig/ → Returns all app configuration pages associated with this app
- GET /:version/appconfig/:id/ → Returns one app configuration page
- PATCH /:version/appconfig/:id/ → Patch an app configuration page
- POST /:version/apps/:id/appconfig/ → Creates an app configuration page for this app
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Appconfig:
    def __init__(self, client: 'CCVClient'):
        """
        App configuration pages are pages used to configure app specific settings or provide support.
        """
        self.client: 'CCVClient' = client

    def delete_an_app_configuration_page(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete an app configuration page
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/appconfig/{id}/",
        )

    def returns_all_app_configuration_pages_associated_with_this_app(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Returns all app configuration pages associated with this app
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/apps/{id}/appconfig/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def returns_one_app_configuration_page(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Returns one app configuration page
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/appconfig/{id}/",
        )

    def patch_an_app_configuration_page(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch an app configuration page
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/appconfig/{id}/",
            body=body,
        )

    def creates_an_app_configuration_page_for_this_app(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates an app configuration page for this app
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/apps/{id}/appconfig/",
            body=body,
        )