"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/basesubscriptions/ → Gives all base subscriptions (ie, Webshop or SalesPOS options).
- OPTIONS /:version/basesubscriptions/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Basesubscriptions(CCVApiEndpoints):
    """
    BaseSubscription are the foundation subscription of a webshop or SalesPOS.
    """

    def gives_all_base_subscriptions_(ie,_webshop_or_salespos_options)(
        self,
    ) -> CCVShopResult:
        """
        Gives all base subscriptions (ie, Webshop or SalesPOS options).
        """
        return self.client._get(
            uri_path="/api/rest/v1/basesubscriptions/",
        )