"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/brands/:id/ → Delete a Brand.
- GET /:version/brands/:id/ → Get one brand.
- GET /:version/brands/ → Get all brands of this webshop.
- OPTIONS /:version/brands/ → None
- PATCH /:version/brands/:id/ → Patch a Brand.
- POST /:version/brands/ → Post a brand.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Brands(CCVApiEndpoints):
    """
    Product brands must have an unique name within the webshop. Products can link to the brand_id.
    """

    def delete_a_brand(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a Brand.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/brands/{id}/",
        )

    def get_one_brand(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one brand.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/brands/{id}/",
        )

    def get_all_brands_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all brands of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/brands/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patch_a_brand(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a Brand.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/brands/{id}/",
            body=body,
        )

    def post_a_brand(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a brand.
        """
        return self.client._post(
            uri_path="/api/rest/v1/brands/",
            body=body,
        )