"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/categorytree/ → Get the complete tree.
- OPTIONS /:version/categorytree/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Categorytree(CCVApiEndpoints):
    """
    The category tree is the collection of all categories. There can be multiple root categories. The tree can be multiple levels deep.
    """

    def get_the_complete_tree(
        self,
    ) -> CCVShopResult:
        """
        Get the complete tree.
        """
        return self.client._get(
            uri_path="/api/rest/v1/categorytree/",
        )