"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/categorytree/ → Get the complete tree
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Categorytree:
    def __init__(self, client: 'CCVClient'):
        """
        The category tree is the collection of all categories. There can be multiple root categories. The tree can be multiple levels deep.
        """
        self.client: 'CCVClient' = client

    def get_the_complete_tree(
        self,
    ) -> CCVShopResult:
        """
        Get the complete tree
        """
        return self.client._get(
            uri_path="/api/rest/v1/categorytree/",
        )