"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/categories/:id/ → Delete a product category.
- GET /:version/categories/:id/categories/ → Get all categories from this category.
- GET /:version/categories/ → Get a collection of product categories.
- GET /:version/categories/:id/ → Get one product category.
- OPTIONS /:version/categories/ → None
- PATCH /:version/categories/:id/ → Patch a product category.
- POST /:version/categories/ → Post a product category.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Categories(CCVApiEndpoints):
    """
    A category can contain other categories or products. Categories with a parent are considered root categories.
    """

    def delete_a_product_category(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a product category.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/categories/{id}/",
        )

    def get_all_categories_from_this_category(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all categories from this category.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/categories/{id}/categories/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_a_collection_of_product_categories(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get a collection of product categories.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/categories/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_product_category(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one product category.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/categories/{id}/",
        )

    def patch_a_product_category(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a product category.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/categories/{id}/",
            body=body,
        )

    def post_a_product_category(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a product category.
        """
        return self.client._post(
            uri_path="/api/rest/v1/categories/",
            body=body,
        )