"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/colors/ → Get all colors. Filters can be applied.
- GET /:version/colors/:id/ → Get one color.
- OPTIONS /:version/colors/ → None
- POST /:version/colors/ → Create a new color based on a hex color code. The hex must be unique.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Colors(CCVApiEndpoints):
    """
    Products can be linked to colors. Colors can be used in product filters for instance. Transparent and Multicolor are also default colors.
    """

    def get_all_colors_filters_can_be_applied(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all colors. Filters can be applied.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/colors/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_color(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one color.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/colors/{id}/",
        )

    def create_a_new_color_based_on_a_hex_color_code_the_hex_must_be_unique(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a new color based on a hex color code. The hex must be unique.
        """
        return self.client._post(
            uri_path="/api/rest/v1/colors/",
            body=body,
        )