"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/conditions/:id/ → Delete a Condition
- GET /:version/conditions/:id/ → Get one condition
- GET /:version/conditions/ → Get all conditions of this webshop
- PATCH /:version/conditions/:id/ → Patch a Condition
- POST /:version/conditions/ → Post a condition
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Conditions:
    def __init__(self, client: 'CCVClient'):
        """
        Product conditions must have an unique name within the webshop. Products can link to the condition_id.
        """
        self.client: 'CCVClient' = client

    def delete_a_condition(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a Condition
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/conditions/{id}/",
        )

    def get_one_condition(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one condition
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/conditions/{id}/",
        )

    def get_all_conditions_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all conditions of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/conditions/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patch_a_condition(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a Condition
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/conditions/{id}/",
            body=body,
        )

    def post_a_condition(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a condition
        """
        return self.client._post(
            uri_path="/api/rest/v1/conditions/",
            body=body,
        )