"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/users/:id/creditpoints/ → Gets a resource with creditpoints and a last mutation date.
- OPTIONS /:version/creditpoints/ → None
- PUT /:version/users/:id/creditpoints/ → Put the creditpoints of a user as is.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Creditpoints(CCVApiEndpoints):
    """
    The creditpoint of a user in the webshop.
    """

    def gets_a_resource_with_creditpoints_and_a_last_mutation_date(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets a resource with creditpoints and a last mutation date.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/users/{id}/creditpoints/",
        )

    def put_the_creditpoints_of_a_user_as_is(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Put the creditpoints of a user as is.
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/users/{id}/creditpoints/",
        )