"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/credentials/:id/ → Deletes current API credential. No futher calls are permitted after this. This is an unreversable action.
- GET /:version/credentials/ → Returns a collection of credentials. This will always be zero or one results.
- GET /:version/credentials/:id/ → Returns the current API credential with the resource id.
- OPTIONS /:version/credentials/ → None
- POST /:version/webshops/:id/credentials/ → Creates a new set API credentials for the parent webshop. Only adminpanel functionality.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Credentials(CCVApiEndpoints):
    """
    Describes current API credential. Not all API credential can retrieve this. Contact CCV Shop if you are interessed in using this resource.
    """

    def deletes_current_api_credential_no_futher_calls_are_permitted_after_this_this_is_an_unreversable_action(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Deletes current API credential. No futher calls are permitted after this. This is an unreversable action.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/credentials/{id}/",
        )

    def returns_a_collection_of_credentials_this_will_always_be_zero_or_one_results(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Returns a collection of credentials. This will always be zero or one results.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/credentials/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def returns_the_current_api_credential_with_the_resource_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Returns the current API credential with the resource id.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/credentials/{id}/",
        )

    def creates_a_new_set_api_credentials_for_the_parent_webshop_only_adminpanel_functionality(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates a new set API credentials for the parent webshop. Only adminpanel functionality.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/webshops/{id}/credentials/",
            body=body,
        )