"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/users/:id/creditpointmutations/ → Gets the creditpoint mutation history of a user.
- GET /:version/creditpointmutations/:id/ → Get one creditpoint mutation.
- OPTIONS /:version/creditpointmutations/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Creditpointmutations(CCVApiEndpoints):
    """
    The creditpoint mutations of a user in the webshop.
    """

    def gets_the_creditpoint_mutation_history_of_a_user(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Gets the creditpoint mutation history of a user.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/users/{id}/creditpointmutations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_creditpoint_mutation(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one creditpoint mutation.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/creditpointmutations/{id}/",
        )