"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/currentsubscriptions/ → Get a collection of current subscriptions. It might be that the subscription has ended.
- GET /:version/currentsubscriptions/:id/ → Get a single current subscriptions. It might be that the subscription has ended.
- OPTIONS /:version/currentsubscriptions/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Currentsubscriptions(CCVApiEndpoints):
    """
    The current subscriptions of a SalesPOS. These might also include ended subscriptions.
    """

    def get_a_collection_of_current_subscriptions_it_might_be_that_the_subscription_has_ended(
        self,
    ) -> CCVShopResult:
        """
        Get a collection of current subscriptions. It might be that the subscription has ended.
        """
        return self.client._get(
            uri_path="/api/rest/v1/currentsubscriptions/",
        )

    def get_a_single_current_subscriptions_it_might_be_that_the_subscription_has_ended(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single current subscriptions. It might be that the subscription has ended.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/currentsubscriptions/{id}/",
        )