"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- OPTIONS /:version/currentuser/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Currentuser(CCVApiEndpoints):
    """
    The current SSO user that is linked to the API credentials of a SalesPOS website.
    """