"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/currentsubscriptions/ → Get a collection of current subscriptions
- GET /:version/currentsubscriptions/:id/ → Get a single current subscriptions
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Currentsubscriptions:
    def __init__(self, client: 'CCVClient'):
        """
        The current subscriptions of a SalesPOS. These might also include ended subscriptions.
        """
        self.client: 'CCVClient' = client

    def get_a_collection_of_current_subscriptions(
        self,
    ) -> CCVShopResult:
        """
        Get a collection of current subscriptions
        """
        return self.client._get(
            uri_path="/api/rest/v1/currentsubscriptions/",
        )

    def get_a_single_current_subscriptions(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single current subscriptions
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/currentsubscriptions/{id}/",
        )