"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Currentuser:
    def __init__(self, client: 'CCVClient'):
        """
        The current SSO user that is linked to the API credentials of a SalesPOS website.
        """
        self.client: 'CCVClient' = client