"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/dashboards/ → Get all dashboards for this user. Each dashboard has a different name (ie location) with different blocks.
- GET /:version/dashboards/:id/ → Get one dashboard.
- OPTIONS /:version/dashboards/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Dashboards(CCVApiEndpoints):
    """
    Dashboards contain blocks that show statistical data from the webshop. They can be managed from the shop backoffice. Not all API keys can retrieve dashboard data. Contact CCV Shop if you are interessed in using this resource.
    """

    def get_all_dashboards_for_this_user_each_dashboard_has_a_different_name_(ie_location)_with_different_blocks(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all dashboards for this user. Each dashboard has a different name (ie location) with different blocks.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/dashboards/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_dashboard(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one dashboard.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/dashboards/{id}/",
        )