"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/dashboards/ → Get all dashboards for this user
- GET /:version/dashboards/:id/ → Get one dashboard
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Dashboards:
    def __init__(self, client: 'CCVClient'):
        """
        Dashboards contain blocks that show statistical data from the webshop. They can be managed from the shop backoffice. Not all API keys can retrieve dashboard data. Contact CCV Shop if you are interessed in using this resource.
        """
        self.client: 'CCVClient' = client

    def get_all_dashboards_for_this_user(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all dashboards for this user
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/dashboards/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_dashboard(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one dashboard
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/dashboards/{id}/",
        )