"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/dashboards/:id/dashboardblocks/ → Get all dashboard blocks from a specific dashboard.
- GET /:version/dashboardblocks/:id/ → Get one dashboard block.
- OPTIONS /:version/dashboardblocks/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Dashboardblocks(CCVApiEndpoints):
    """
    Dashboard blocks are statistical blocks of a dashboard. They contain a value on a context. They might be a fixed number or a relative number or a percentage.
    """

    def get_all_dashboard_blocks_from_a_specific_dashboard(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all dashboard blocks from a specific dashboard.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/dashboards/{id}/dashboardblocks/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_dashboard_block(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one dashboard block.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/dashboardblocks/{id}/",
        )