"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/usergroups/:id/disabledpaymethods/ → Get all disabled paymethods for this user group.
- GET /:version/users/:id/disabledpaymethods/ → Get all disabled paymethods for this user. The result will be empty if the user belongs to a group.
- OPTIONS /:version/disabledpaymethods/ → None
- PUT /:version/usergroups/:id/disabledpaymethods/ → Change the disabled paymethods for an user group. Paymethods that are enabled in the webshop but are omitted here are visible for the user during the checkout.
- PUT /:version/users/:id/disabledpaymethods/ → Change the disabled paymethods for an user. Paymethods that are enabled in the webshop but are omitted here are visible for the user during the checkout. Gives an exception if the user belongs to a group.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Disabledpaymethods(CCVApiEndpoints):
    """
    Describes a disabled paymethod for a specific user or user group. This paymethod is hidden for the user or all users within a gropup during the checkout. See the resource /paymethods for available options.
    """

    def get_all_disabled_paymethods_for_this_user_group(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all disabled paymethods for this user group.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/usergroups/{id}/disabledpaymethods/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_all_disabled_paymethods_for_this_user_the_result_will_be_empty_if_the_user_belongs_to_a_group(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all disabled paymethods for this user. The result will be empty if the user belongs to a group.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/users/{id}/disabledpaymethods/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def change_the_disabled_paymethods_for_an_user_group_paymethods_that_are_enabled_in_the_webshop_but_are_omitted_here_are_visible_for_the_user_during_the_checkout(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Change the disabled paymethods for an user group. Paymethods that are enabled in the webshop but are omitted here are visible for the user during the checkout.
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/usergroups/{id}/disabledpaymethods/",
        )

    def change_the_disabled_paymethods_for_an_user_paymethods_that_are_enabled_in_the_webshop_but_are_omitted_here_are_visible_for_the_user_during_the_checkout_gives_an_exception_if_the_user_belongs_to_a_group(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Change the disabled paymethods for an user. Paymethods that are enabled in the webshop but are omitted here are visible for the user during the checkout. Gives an exception if the user belongs to a group.
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/users/{id}/disabledpaymethods/",
        )