"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/discountcoupons/:id/ → Delete a discount coupon.
- GET /:version/discountcoupons/ → Get all discount coupons of this webshop.
- GET /:version/discountcoupons/:id/ → Get one discount coupon.
- OPTIONS /:version/discountcoupons/ → None
- POST /:version/discountcoupons/ → Add a discount coupon.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Discountcoupons(CCVApiEndpoints):
    """
    Discount coupons are codes that customers can add in their basket to get a discout or free shipping.
    """

    def delete_a_discount_coupon(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a discount coupon.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/discountcoupons/{id}/",
        )

    def get_all_discount_coupons_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all discount coupons of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/discountcoupons/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_discount_coupon(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one discount coupon.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/discountcoupons/{id}/",
        )

    def add_a_discount_coupon(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Add a discount coupon.
        """
        return self.client._post(
            uri_path="/api/rest/v1/discountcoupons/",
            body=body,
        )