"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/domains/ → Get all domains for a specific webshop.
- OPTIONS /:version/domains/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Domains(CCVApiEndpoints):
    """
    This describes the domains for a webshop.
    """

    def get_all_domains_for_a_specific_webshop(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get all domains for a specific webshop.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/webshops/{id}/domains/",
        )