"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/domains/ → Get all domains for a specific webshop
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Domains:
    def __init__(self, client: 'CCVClient'):
        """
        This describes the domains for a webshop.
        """
        self.client: 'CCVClient' = client

    def get_all_domains_for_a_specific_webshop(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get all domains for a specific webshop
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/webshops/{id}/domains/",
        )