"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orders/:id/fiscaltransactionsignatures/ → Get all fiscal transaction signatures from this order
- GET /:version/fiscaltransactionsignatures/:id/ → Get a single fiscal transaction signature from this SalesPOS
- PATCH /:version/fiscaltransactionsignatures/:id/ → Patch a fiscal transaction signature
- POST /:version/orders/:id/fiscaltransactionsignatures/ → Creates an fiscal transaction signatures linked to an order
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Fiscaltransactionsignatures:
    def __init__(self, client: 'CCVClient'):
        """
        The fiscal transaction signatures are blocks of obligatory data that will be added to a receipt. They are linked to orders. They contain different versions for different purposes.
        """
        self.client: 'CCVClient' = client

    def get_all_fiscal_transaction_signatures_from_this_order(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get all fiscal transaction signatures from this order
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/orders/{id}/fiscaltransactionsignatures/",
        )

    def get_a_single_fiscal_transaction_signature_from_this_salespos(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single fiscal transaction signature from this SalesPOS
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/fiscaltransactionsignatures/{id}/",
        )

    def patch_a_fiscal_transaction_signature(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a fiscal transaction signature
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/fiscaltransactionsignatures/{id}/",
            body=body,
        )

    def creates_an_fiscal_transaction_signatures_linked_to_an_order(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates an fiscal transaction signatures linked to an order
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orders/{id}/fiscaltransactionsignatures/",
            body=body,
        )