"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/geozonecountries/ → Retrieve all countries of the webshop's geozones.
- OPTIONS /:version/geozonecountries/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Geozonecountries(CCVApiEndpoints):
    """
    This describes the geozone countries for a webshop.
    """

    def retrieve_all_countries_of_the_webshop's_geozones(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Retrieve all countries of the webshop's geozones.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/webshops/{id}/geozonecountries/",
        )