"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/invoices/:id/invoicerows/ → Get all invoice rows of this invoice.
- GET /:version/invoicerows/:id/ → Get one invoice row.
- OPTIONS /:version/invoicerows/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Invoicerows(CCVApiEndpoints):
    """
    These are the invoice rows of an invoice.
    """

    def get_all_invoice_rows_of_this_invoice(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all invoice rows of this invoice.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/invoices/{id}/invoicerows/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_invoice_row(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one invoice row.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/invoicerows/{id}/",
        )