"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/invoices/:id/invoicenotifications/ → Get all order notifications belonging to an order.
- GET /:version/invoicenotifications/:id/ → Get one order notification based on an Id.
- OPTIONS /:version/invoicenotifications/ → None
- POST /:version/invoices/:id/invoicenotifications/ → Create a order notification of the given type. This will trigger an e-mail of the given type.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Invoicenotifications(CCVApiEndpoints):
    """
    Invoice notifications are used to send e-mails of the different types. For instance, an invoice can be sent to the customer. GET will return all previous notifications created by the API.
    """

    def get_all_order_notifications_belonging_to_an_order(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all order notifications belonging to an order.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/invoices/{id}/invoicenotifications/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_order_notification_based_on_an_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one order notification based on an Id.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/invoicenotifications/{id}/",
        )

    def create_a_order_notification_of_the_given_type_this_will_trigger_an_e-mail_of_the_given_type(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a order notification of the given type. This will trigger an e-mail of the given type.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/invoices/{id}/invoicenotifications/",
            body=body,
        )