"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/invoices/:id/invoicerows/ → Get all invoice rows of this invoice
- GET /:version/invoicerows/:id/ → Get one invoice row
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Invoicerows:
    def __init__(self, client: 'CCVClient'):
        """
        These are the invoice rows of an invoice.
        """
        self.client: 'CCVClient' = client

    def get_all_invoice_rows_of_this_invoice(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all invoice rows of this invoice
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/invoices/{id}/invoicerows/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_invoice_row(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one invoice row
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/invoicerows/{id}/",
        )