"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/invoices/ → Get all invoices of this webshop.
- GET /:version/invoices/:id/ → Get one invoices by id.
- OPTIONS /:version/invoices/ → None
- PATCH /:version/invoices/:id/ → Patch an invoice.
- POST /:version/orders/:id/invoices/ → Create an invoice for this order. With a post action an invoice is created based on the difference between the current order and the most recent invoice.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Invoices(CCVApiEndpoints):
    """
    These are the invoices of a webshop But this could also be used to do a POST or only get one invoice.
    """

    def get_all_invoices_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all invoices of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/invoices/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_invoices_by_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one invoices by id.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/invoices/{id}/",
        )

    def patch_an_invoice(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch an invoice.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/invoices/{id}/",
            body=body,
        )

    def create_an_invoice_for_this_order_with_a_post_action_an_invoice_is_created_based_on_the_difference_between_the_current_order_and_the_most_recent_invoice(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create an invoice for this order. With a post action an invoice is created based on the difference between the current order and the most recent invoice.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orders/{id}/invoices/",
            body=body,
        )