"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/languages/ → Get all available languages.
- OPTIONS /:version/languages/ → None
- POST /:version/languages/ → Creates a new languages based upon an existing one.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Languages(CCVApiEndpoints):
    """
    All available languages in the webshop. You can also create a new language with this resource.
    """

    def get_all_available_languages(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all available languages.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/languages/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def creates_a_new_languages_based_upon_an_existing_one(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates a new languages based upon an existing one.
        """
        return self.client._post(
            uri_path="/api/rest/v1/languages/",
            body=body,
        )