"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/languages/ → Get all available languages
- POST /:version/languages/ → Creates a new languages based upon an existing one
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Languages:
    def __init__(self, client: 'CCVClient'):
        """
        All available languages in the webshop. You can also create a new language with this resource.
        """
        self.client: 'CCVClient' = client

    def get_all_available_languages(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all available languages
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/languages/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def creates_a_new_languages_based_upon_an_existing_one(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates a new languages based upon an existing one
        """
        return self.client._post(
            uri_path="/api/rest/v1/languages/",
            body=body,
        )