"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/mailinglists/:id/ → Delete a mailinglist
- GET /:version/mailinglists/:id/ → Get one mailinglist
- GET /:version/mailinglists/ → Get all mailinglists of this webshop
- PATCH /:version/mailinglists/:id/ → Patch a mailinglist
- POST /:version/mailinglists/ → Post a mailinglist
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Mailinglists:
    def __init__(self, client: 'CCVClient'):
        """
        The mailinglists of the webshop, containing mailingaddresses.
        """
        self.client: 'CCVClient' = client

    def delete_a_mailinglist(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a mailinglist
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/mailinglists/{id}/",
        )

    def get_one_mailinglist(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one mailinglist
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/mailinglists/{id}/",
        )

    def get_all_mailinglists_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all mailinglists of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/mailinglists/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patch_a_mailinglist(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a mailinglist
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/mailinglists/{id}/",
            body=body,
        )

    def post_a_mailinglist(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a mailinglist
        """
        return self.client._post(
            uri_path="/api/rest/v1/mailinglists/",
            body=body,
        )