"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/marktplaatscategories/:id/ → Get one Marktplaats category
- GET /:version/marktplaatscategories/ → Get all Marktplaats categories
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Marktplaatscategories:
    def __init__(self, client: 'CCVClient'):
        """
        These are the categories Marktplaats provides. This is required when products are exported to Marktplaats.
        """
        self.client: 'CCVClient' = client

    def get_one_marktplaats_category(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one Marktplaats category
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/marktplaatscategories/{id}/",
        )

    def get_all_marktplaats_categories(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all Marktplaats categories
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/marktplaatscategories/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )