"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/merchant/ → Get merchant data associated with this webshop.
- GET /:version/merchant/:id/ → Get a single Merchant. Adminpanel functionality only.
- GET /:version/merchant/ → Get all merchants. Adminpanel functionality only.
- OPTIONS /:version/merchant/ → None
- PATCH /:version/merchant/:id/ → Patches merchant Data. Adminpanel functionality only.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Merchant(CCVApiEndpoints):
    """
    Describes the merchant data of this webshop.
    """

    def get_merchant_data_associated_with_this_webshop(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get merchant data associated with this webshop.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/webshops/{id}/merchant/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_a_single_merchant_adminpanel_functionality_only(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single Merchant. Adminpanel functionality only.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/merchant/{id}/",
        )

    def get_all_merchants_adminpanel_functionality_only(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all merchants. Adminpanel functionality only.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/merchant/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patches_merchant_data_adminpanel_functionality_only(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patches merchant Data. Adminpanel functionality only.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/merchant/{id}/",
            body=body,
        )