"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orders/:id/orderlabels/ → Get all labels linked to this order.
- OPTIONS /:version/orderlabels/ → None
- PUT /:version/orders/:id/orderlabels/ → Replaces all labels of this order with the new collection. An empty collection can be used to remove all labels.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Orderlabels(CCVApiEndpoints):
    """
    Describes link between a label and an order. These labels will be shown with these orders.
    """

    def get_all_labels_linked_to_this_order(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all labels linked to this order.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/orders/{id}/orderlabels/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def replaces_all_labels_of_this_order_with_the_new_collection_an_empty_collection_can_be_used_to_remove_all_labels(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Replaces all labels of this order with the new collection. An empty collection can be used to remove all labels.
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/orders/{id}/orderlabels/",
        )