"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/ordernotes/:id/ → Delete one notes of an order.
- GET /:version/orders/:id/ordernotes/ → Get all notes of this order.
- GET /:version/ordernotes/:id/ → Get one notes of an order.
- OPTIONS /:version/ordernotes/ → None
- POST /:version/orders/:id/ordernotes/ → Creates an internal note on one order.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Ordernotes(CCVApiEndpoints):
    """
    These are notes that can be added to an order. External notes were also sent to the consumer.
    """

    def delete_one_notes_of_an_order(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete one notes of an order.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/ordernotes/{id}/",
        )

    def get_all_notes_of_this_order(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all notes of this order.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/orders/{id}/ordernotes/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_notes_of_an_order(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one notes of an order.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/ordernotes/{id}/",
        )

    def creates_an_internal_note_on_one_order(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates an internal note on one order.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orders/{id}/ordernotes/",
            body=body,
        )