"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orderrowcalculator/:id/ → Get an orderrow calculator.
- OPTIONS /:version/orderrowcalculator/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Orderrowcalculator(CCVApiEndpoints):
    """
    Calculator values for an orderrow.
    """

    def get_an_orderrow_calculator(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get an orderrow calculator.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/orderrowcalculator/{id}/",
        )