"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orders/ → Get all orders of this webshop.
- GET /:version/orders/:id/ → Get one order of this webshop.
- OPTIONS /:version/orders/ → None
- PATCH /:version/orders/:id/ → Patch an existing order.
- POST /:version/orders/ → Post a new order.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Orders(CCVApiEndpoints):
    """
    These are the orders in the webshop, either ordered by the customer or handmade in the backend.
    """

    def get_all_orders_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all orders of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/orders/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_order_of_this_webshop(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one order of this webshop.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/orders/{id}/",
        )

    def patch_an_existing_order(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch an existing order.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/orders/{id}/",
            body=body,
        )

    def post_a_new_order(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a new order.
        """
        return self.client._post(
            uri_path="/api/rest/v1/orders/",
            body=body,
        )