"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/ordermessages/:id/ → Delete one specific message.
- GET /:version/orders/:id/ordermessages/ → Get all messages from this order.
- GET /:version/ordermessages/:id/ → Get one specific message.
- OPTIONS /:version/ordermessages/ → None
- POST /:version/orders/:id/ordermessages/ → Create a new order message. This message will also be emailed to the customer.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Ordermessages(CCVApiEndpoints):
    """
    Order messages are sent to the customer.
    """

    def delete_one_specific_message(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete one specific message.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/ordermessages/{id}/",
        )

    def get_all_messages_from_this_order(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all messages from this order.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/orders/{id}/ordermessages/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_specific_message(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one specific message.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/ordermessages/{id}/",
        )

    def create_a_new_order_message_this_message_will_also_be_emailed_to_the_customer(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a new order message. This message will also be emailed to the customer.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orders/{id}/ordermessages/",
            body=body,
        )