"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orders/:id/orderaffiliatenetworks/ → Get all order rows of this order
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Orderaffiliatenetworks:
    def __init__(self, client: 'CCVClient'):
        """
        An Affiliate network is a network which can be installed by either ann app or by a third party. When accesing the page with a specifik network name, it will be saved by the order which the customer makes on the website.
        """
        self.client: 'CCVClient' = client

    def get_all_order_rows_of_this_order(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all order rows of this order
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/orders/{id}/orderaffiliatenetworks/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )