"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orders/:id/orderaffiliatenetworks/ → Get all order rows of this order.
- OPTIONS /:version/orderaffiliatenetworks/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Orderaffiliatenetworks(CCVApiEndpoints):
    """
    An Affiliate network is a network which can be installed by either ann app or by a third party. When accesing the page with a specifik network name, it will be saved by the order which the customer makes on the website.
    """

    def get_all_order_rows_of_this_order(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all order rows of this order.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/orders/{id}/orderaffiliatenetworks/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )