"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/paymethods/ → Get all paymethods that are activated in the webshop.
- OPTIONS /:version/paymethods/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Paymethods(CCVApiEndpoints):
    """
    Paymethod that are activated in the webshop. Customers can choose to pay with them.
    """

    def get_all_paymethods_that_are_activated_in_the_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all paymethods that are activated in the webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/paymethods/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )