"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/productstaggeredprices/:id/ → Delete a staggered price row.
- GET /:version/products/:id/productstaggeredprices/ → Get all straggered price rows of a product.
- GET /:version/productstaggeredprices/:id/ → Get one staggered price row.
- OPTIONS /:version/productstaggeredprices/ → None
- PATCH /:version/productstaggeredprices/:id/ → Patch a staggered price row.
- POST /:version/products/:id/productstaggeredprices/ → Post a staggered price row for this product.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productstaggeredprices(CCVApiEndpoints):
    """
    Staggered prices are prices and discounts that change when ordered quantity of the product changes.
    """

    def delete_a_staggered_price_row(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a staggered price row.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/productstaggeredprices/{id}/",
        )

    def get_all_straggered_price_rows_of_a_product(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get all straggered price rows of a product.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/products/{id}/productstaggeredprices/",
        )

    def get_one_staggered_price_row(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one staggered price row.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/productstaggeredprices/{id}/",
        )

    def patch_a_staggered_price_row(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a staggered price row.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/productstaggeredprices/{id}/",
            body=body,
        )

    def post_a_staggered_price_row_for_this_product(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a staggered price row for this product.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/products/{id}/productstaggeredprices/",
            body=body,
        )