"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/products/:id/productattributesets/ → Get all attribute sets of this product with the underlaying attribute values.
- OPTIONS /:version/productattributesets/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productattributesets(CCVApiEndpoints):
    """
    This is a collection of all attribute sets of this product with the underlaying attribute values.
    """

    def get_all_attribute_sets_of_this_product_with_the_underlaying_attribute_values(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all attribute sets of this product with the underlaying attribute values.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/productattributesets/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )