"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/products/:id/productkeywords/ → Delete all keywords from this product.
- GET /:version/products/:id/productkeywords/ → Get all keywords for this product.
- OPTIONS /:version/productkeywords/ → None
- POST /:version/products/:id/productkeywords/ → Post a product keyword.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productkeywords(CCVApiEndpoints):
    """
    Product keywords are keywords that are used by the internal search engine of the webshop and displayed in the tagcloud.
    """

    def delete_all_keywords_from_this_product(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete all keywords from this product.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/products/{id}/productkeywords/",
        )

    def get_all_keywords_for_this_product(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all keywords for this product.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/productkeywords/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def post_a_product_keyword(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a product keyword.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/products/{id}/productkeywords/",
            body=body,
        )