"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/products/:id/productattributesets/ → Get all attribute sets of this product with the underlaying attribute values
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Productattributesets:
    def __init__(self, client: 'CCVClient'):
        """
        This is a collection of all attribute sets of this product with the underlaying attribute values.
        """
        self.client: 'CCVClient' = client

    def get_all_attribute_sets_of_this_product_with_the_underlaying_attribute_values(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all attribute sets of this product with the underlaying attribute values
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/productattributesets/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )