"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/products/:id/productshippingcosts/ → Retrieve all shipping costs to the possible countries this product can be shipped to
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Productshippingcosts:
    def __init__(self, client: 'CCVClient'):
        """
        A collection of shipping costs to the possible countries this product can be shipped to.
        """
        self.client: 'CCVClient' = client

    def retrieve_all_shipping_costs_to_the_possible_countries_this_product_can_be_shipped_to(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Retrieve all shipping costs to the possible countries this product can be shipped to
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/productshippingcosts/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )