"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/productpropertyoptions/:id/ → Delete a Product property option.
- GET /:version/productproperties/:id/productpropertyoptions/ → Get all product property options that belong to this property.
- GET /:version/productpropertyoptions/:id/ → Get one Product property option.
- OPTIONS /:version/productpropertyoptions/ → None
- PATCH /:version/productpropertyoptions/:id/ → Patch a product Product property option.
- POST /:version/productproperties/:id/productpropertyoptions/ → Post a product property options that belong to this property.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productpropertyoptions(CCVApiEndpoints):
    """
    A Product property option, these are values of a property with the type option.
    """

    def delete_a_product_property_option(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a Product property option.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/productpropertyoptions/{id}/",
        )

    def get_all_product_property_options_that_belong_to_this_property(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all product property options that belong to this property.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/productproperties/{id}/productpropertyoptions/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_product_property_option(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one Product property option.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/productpropertyoptions/{id}/",
        )

    def patch_a_product_product_property_option(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a product Product property option.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/productpropertyoptions/{id}/",
            body=body,
        )

    def post_a_product_property_options_that_belong_to_this_property(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a product property options that belong to this property.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/productproperties/{id}/productpropertyoptions/",
            body=body,
        )