"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/productpropertyvalues/:id/ → Delete a product property value.
- GET /:version/productpropertyvalues/:id/ → Get one product property value.
- OPTIONS /:version/productpropertyvalues/ → None
- PATCH /:version/productpropertyvalues/:id/ → Patch a product Product property value.
- POST /:version/productpropertyvalues/ → Post a product property value.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productpropertyvalues(CCVApiEndpoints):
    """
    A Product property value can hold multiple properties.
    """

    def delete_a_product_property_value(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a product property value.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/productpropertyvalues/{id}/",
        )

    def get_one_product_property_value(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one product property value.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/productpropertyvalues/{id}/",
        )

    def patch_a_product_product_property_value(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a product Product property value.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/productpropertyvalues/{id}/",
            body=body,
        )

    def post_a_product_property_value(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a product property value.
        """
        return self.client._post(
            uri_path="/api/rest/v1/productpropertyvalues/",
            body=body,
        )