"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/productqueries/ → Retrieve all products and attribute combinations based on the parameters. At least one parameter is required to give results. Note: mpnnumber doesn't exist for attribute combinations and skunumber doesn't exist for products.
- OPTIONS /:version/productqueries/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productqueries(CCVApiEndpoints):
    """
    With this resource you can query for products and attribute combinations with certain parameters. If a parameter is found in an attribute combination then the whole product object with just that one combination will be return. Multiple results are possible. This resource is not designed to be used for data synchronization but meant to be trigger on manual input from a user (for instance with a barcode scanner).
    """

    def retrieve_all_products_and_attribute_combinations_based_on_the_parameters_at_least_one_parameter_is_required_to_give_results_note:_mpnnumber_doesn't_exist_for_attribute_combinations_and_skunumber_doesn't_exist_for_products(
        self,
    ) -> CCVShopResult:
        """
        Retrieve all products and attribute combinations based on the parameters. At least one parameter is required to give results. Note: mpnnumber doesn't exist for attribute combinations and skunumber doesn't exist for products.
        """
        return self.client._get(
            uri_path="/api/rest/v1/productqueries/",
        )