"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/producttopropertygroups/:id/ → Delete a product to product property group link
- GET /:version/products/:id/producttopropertygroups/ → Get all product property groups of this product
- GET /:version/producttopropertygroups/:id/ → Get a  product to product property group link
- POST /:version/producttopropertygroups/ → Create a new product to product property group link
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Producttopropertygroups:
    def __init__(self, client: 'CCVClient'):
        """
        Get or create a product 2 productproperty group, this is the link between both, and the place where you can add values.
        """
        self.client: 'CCVClient' = client

    def delete_a_product_to_product_property_group_link(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a product to product property group link
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/producttopropertygroups/{id}/",
        )

    def get_all_product_property_groups_of_this_product(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all product property groups of this product
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/producttopropertygroups/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_a__product_to_product_property_group_link(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a  product to product property group link
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/producttopropertygroups/{id}/",
        )

    def create_a_new_product_to_product_property_group_link(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a new product to product property group link
        """
        return self.client._post(
            uri_path="/api/rest/v1/producttopropertygroups/",
            body=body,
        )