"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/products/:id/productshippingcosts/ → Retrieve all shipping costs to the possible countries this product can be shipped to.
- OPTIONS /:version/productshippingcosts/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productshippingcosts(CCVApiEndpoints):
    """
    A collection of shipping costs to the possible countries this product can be shipped to.
    """

    def retrieve_all_shipping_costs_to_the_possible_countries_this_product_can_be_shipped_to(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Retrieve all shipping costs to the possible countries this product can be shipped to.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/productshippingcosts/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )