"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/productrelevant/:id/ → Delete one relevant product. Note: this will not delete the product itsself.
- GET /:version/products/:id/productrelevant/ → Get all relevant products of this product.
- GET /:version/productrelevant/:id/ → Get one relevant product.
- OPTIONS /:version/productrelevant/ → None
- POST /:version/products/:id/productrelevant/ → Create a relevant product. Note: This will not create a new product.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productrelevant(CCVApiEndpoints):
    """
    A product can have other products marked as 'relevant'. These products will be shown on the product page.
    """

    def delete_one_relevant_product_note:_this_will_not_delete_the_product_itsself(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete one relevant product. Note: this will not delete the product itsself.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/productrelevant/{id}/",
        )

    def get_all_relevant_products_of_this_product(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get all relevant products of this product.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/products/{id}/productrelevant/",
        )

    def get_one_relevant_product(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one relevant product.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/productrelevant/{id}/",
        )

    def create_a_relevant_product_note:_this_will_not_create_a_new_product(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a relevant product. Note: This will not create a new product.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/products/{id}/productrelevant/",
            body=body,
        )