"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/productqueries/ → Retrieve all products and attribute combinations based on the parameters
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Productqueries:
    def __init__(self, client: 'CCVClient'):
        """
        With this resource you can query for products and attribute combinations with certain parameters. If a parameter is found in an attribute combination then the whole product object with just that one combination will be return. Multiple results are possible. This resource is not designed to be used for data synchronization but meant to be trigger on manual input from a user (for instance with a barcode scanner).
        """
        self.client: 'CCVClient' = client

    def retrieve_all_products_and_attribute_combinations_based_on_the_parameters(
        self,
    ) -> CCVShopResult:
        """
        Retrieve all products and attribute combinations based on the parameters
        """
        return self.client._get(
            uri_path="/api/rest/v1/productqueries/",
        )