"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/productvariations/:id/ → Delete a variation. Variations created based on product number are marked as auto_created and can't be deleted.
- GET /:version/products/:id/productvariations/ → Get all variations from this product.
- GET /:version/productvariations/:id/ → Get a single variation.
- OPTIONS /:version/productvariations/ → None
- PATCH /:version/productvariations/:id/ → Update an exisiting variation.
- POST /:version/products/:id/productvariations/ → Add a new variation to this product.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Productvariations(CCVApiEndpoints):
    """
    A product variation is a link to another similar product, but in a different colour for instance. The link is bidirectional, if Product A is linked to B, B is linked to A. Inactive variations are hidden in the webshop. Variations created based on product number are marked as auto_created.
    """

    def delete_a_variation_variations_created_based_on_product_number_are_marked_as_auto_created_and_can't_be_deleted(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a variation. Variations created based on product number are marked as auto_created and can't be deleted.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/productvariations/{id}/",
        )

    def get_all_variations_from_this_product(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all variations from this product.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/products/{id}/productvariations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_a_single_variation(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single variation.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/productvariations/{id}/",
        )

    def update_an_exisiting_variation(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Update an exisiting variation.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/productvariations/{id}/",
            body=body,
        )

    def add_a_new_variation_to_this_product(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Add a new variation to this product.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/products/{id}/productvariations/",
            body=body,
        )