"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/quotations/:id/quotationrows/ → Get all invoice rows of this invoice.
- GET /:version/quotationrows/:id/ → Get one QuotationRow.
- OPTIONS /:version/quotationrows/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Quotationrows(CCVApiEndpoints):
    """
    These are the quotation rows of a quotation.
    """

    def get_all_invoice_rows_of_this_invoice(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all invoice rows of this invoice.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/quotations/{id}/quotationrows/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_quotationrow(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one QuotationRow.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/quotationrows/{id}/",
        )