"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/quotations/ → Get all quotations of this webshop.
- GET /:version/quotations/:id/ → Get one Quotation.
- OPTIONS /:version/quotations/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Quotations(CCVApiEndpoints):
    """
    These are the quotations of a webshop.
    """

    def get_all_quotations_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all quotations of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/quotations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_quotation(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one Quotation.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/quotations/{id}/",
        )