"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/returns/:id/returnrows/ → Get all return rows of this return.
- GET /:version/returnrows/:id/ → Get one return row.
- OPTIONS /:version/returnrows/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Returnrows(CCVApiEndpoints):
    """
    These are the return rows of a webshop.
    """

    def get_all_return_rows_of_this_return(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all return rows of this return.
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/returns/{id}/returnrows/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_return_row(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one return row.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/returnrows/{id}/",
        )