"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/returns/ → Get all returns of this webshop.
- GET /:version/returns/:id/ → Get one return object .
- OPTIONS /:version/returns/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Returns(CCVApiEndpoints):
    """
    These are the returns of a webshop.
    """

    def get_all_returns_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all returns of this webshop.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/returns/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_return_object_(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one return object .
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/returns/{id}/",
        )