"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/ → Get all available resources for this public key.
- OPTIONS /:version/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Root(CCVApiEndpoints):
    """
    This is a collection of available resources for this Public Key.
    """

    def get_all_available_resources_for_this_public_key(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all available resources for this public key.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )