"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/servicecategories/:id/services/ → Get all apps associated by this categorie id
- GET /:version/services/:id/ → Gets one service associated with this apikey
- GET /:version/services/ → Gets all apps associated with this apikey
- PATCH /:version/services/:id/ → Updates an existing app
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Services:
    def __init__(self, client: 'CCVClient'):
        """
        These are businesses that offer additional services for a webshop.
        """
        self.client: 'CCVClient' = client

    def get_all_apps_associated_by_this_categorie_id(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all apps associated by this categorie id
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/servicecategories/{id}/services/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def gets_one_service_associated_with_this_apikey(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets one service associated with this apikey
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/services/{id}/",
        )

    def gets_all_apps_associated_with_this_apikey(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Gets all apps associated with this apikey
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/services/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def updates_an_existing_app(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Updates an existing app
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/services/{id}/",
            body=body,
        )