"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/servicecategories/:id/ → Gets one appstore categorie.
- GET /:version/servicecategories/ → Gets all appsstore categories.
- OPTIONS /:version/servicecategories/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Servicecategories(CCVApiEndpoints):
    """
    These are alle the services categories.
    """

    def gets_one_appstore_categorie(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets one appstore categorie.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/servicecategories/{id}/",
        )

    def gets_all_appsstore_categories(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Gets all appsstore categories.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/servicecategories/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )