"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/settings/ → Retrieve all settings of the webshop.
- OPTIONS /:version/settings/ → None
- PUT /:version/webshops/:id/settings/ → You can override the current values of certain settings. Only settings that are included in the payload will be overwritten.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Settings(CCVApiEndpoints):
    """
    Describes the settings of this webshop.
    """

    def retrieve_all_settings_of_the_webshop(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Retrieve all settings of the webshop.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/webshops/{id}/settings/",
        )

    def you_can_override_the_current_values_of_certain_settings_only_settings_that_are_included_in_the_payload_will_be_overwritten(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        You can override the current values of certain settings. Only settings that are included in the payload will be overwritten.
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/webshops/{id}/settings/",
        )