"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/settings/ → Retrieve all settings of the webshop
- PUT /:version/webshops/:id/settings/ → You can override the current values of certain settings
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Settings:
    def __init__(self, client: 'CCVClient'):
        """
        Describes the settings of this webshop.
        """
        self.client: 'CCVClient' = client

    def retrieve_all_settings_of_the_webshop(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Retrieve all settings of the webshop
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/webshops/{id}/settings/",
        )

    def you_can_override_the_current_values_of_certain_settings(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        You can override the current values of certain settings
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/webshops/{id}/settings/",
            body=body,
        )