"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/status/ → Get status of the API.
- OPTIONS /:version/status/ → None
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Status(CCVApiEndpoints):
    """
    Displays status information about this API.
    """

    def get_status_of_the_api(
        self,
    ) -> CCVShopResult:
        """
        Get status of the API.
        """
        return self.client._get(
            uri_path="/api/rest/v1/status/",
        )