"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/status/ → Get status of the API
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Status:
    def __init__(self, client: 'CCVClient'):
        """
        Displays status information about this API.
        """
        self.client: 'CCVClient' = client

    def get_status_of_the_api(
        self,
    ) -> CCVShopResult:
        """
        Get status of the API
        """
        return self.client._get(
            uri_path="/api/rest/v1/status/",
        )