"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- OPTIONS /:version/subscriptionupgrades/ → None
- POST /:version/subscriptionupgrades/ → Post a subscription upgrade, changing the current SalesPOS subscription.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Subscriptionupgrades(CCVApiEndpoints):
    """
    Can do an upgrade of the current SalesPOS subscription to a new subscription. For instance from sales_pos_trial to sales_pos.
    """

    def post_a_subscription_upgrade,_changing_the_current_salespos_subscription(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a subscription upgrade, changing the current SalesPOS subscription.
        """
        return self.client._post(
            uri_path="/api/rest/v1/subscriptionupgrades/",
            body=body,
        )