"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/subscriptiondiscountcoupons/:id/ → Get one Subscription Discount Coupon
- GET /:version/subscriptiondiscountcoupons/ → Get all Subscription Discount Coupons
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Subscriptiondiscountcoupons:
    def __init__(self, client: 'CCVClient'):
        """
        When upgrading a subscription there is a posiblity to add a discount coupon. This resource can be used to check if the coupon is valid.
        """
        self.client: 'CCVClient' = client

    def get_one_subscription_discount_coupon(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one Subscription Discount Coupon
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/subscriptiondiscountcoupons/{id}/",
        )

    def get_all_subscription_discount_coupons(
        self,
    ) -> CCVShopResult:
        """
        Get all Subscription Discount Coupons
        """
        return self.client._get(
            uri_path="/api/rest/v1/subscriptiondiscountcoupons/",
        )