"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/suppliers/:id/ → Delete a Supplier
- GET /:version/suppliers/:id/ → Get one supplier
- GET /:version/suppliers/ → Get all suppliers of this webshop
- PATCH /:version/suppliers/:id/ → Patch a Supplier
- POST /:version/suppliers/ → Post a supplier
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Suppliers:
    def __init__(self, client: 'CCVClient'):
        """
        Product suppliers must have an unique name within the webshop. Products can link to the supplier_id.
        """
        self.client: 'CCVClient' = client

    def delete_a_supplier(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete a Supplier
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/suppliers/{id}/",
        )

    def get_one_supplier(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one supplier
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/suppliers/{id}/",
        )

    def get_all_suppliers_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all suppliers of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/suppliers/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patch_a_supplier(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch a Supplier
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/suppliers/{id}/",
            body=body,
        )

    def post_a_supplier(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a supplier
        """
        return self.client._post(
            uri_path="/api/rest/v1/suppliers/",
            body=body,
        )