"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/terminalreceipts/ → Get all transaction receipts from this SalesPOS.
- GET /:version/terminalreceipts/:id/ → Get a single transaction receipts from this SalesPOS.
- OPTIONS /:version/terminalreceipts/ → None
- POST /:version/orders/:id/terminalreceipts/ → Creates terminal receipts for a single order.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Terminalreceipts(CCVApiEndpoints):
    """
    Terminal Receipts are created by the terminal on a transaction. They are linked to orders. They contain different versions for different purposes.
    """

    def get_all_transaction_receipts_from_this_salespos(
        self,
    ) -> CCVShopResult:
        """
        Get all transaction receipts from this SalesPOS.
        """
        return self.client._get(
            uri_path="/api/rest/v1/terminalreceipts/",
        )

    def get_a_single_transaction_receipts_from_this_salespos(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single transaction receipts from this SalesPOS.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/terminalreceipts/{id}/",
        )

    def creates_terminal_receipts_for_a_single_order(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates terminal receipts for a single order.
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orders/{id}/terminalreceipts/",
            body=body,
        )