"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/translations/ → Get all translations keys and values
- PUT /:version/translations/ → Overwrites the current value of a language of a key
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Translations:
    def __init__(self, client: 'CCVClient'):
        """
        Translations of all texts in the frontend of the webshop. Each object contains the translation of the current accept language.
        """
        self.client: 'CCVClient' = client

    def get_all_translations_keys_and_values(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all translations keys and values
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/translations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def overwrites_the_current_value_of_a_language_of_a_key(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Overwrites the current value of a language of a key
        """
        return self.client._put(
            uri_path="/api/rest/v1/translations/",
            body=body,
        )