"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/translations/ → Get all translations keys and values. Translation will be based on accept language.
- OPTIONS /:version/translations/ → None
- PUT /:version/translations/ → Overwrites the current value of a language of a key. The translation will be applied to the accept language.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Translations(CCVApiEndpoints):
    """
    Translations of all texts in the frontend of the webshop. Each object contains the translation of the current accept language.
    """

    def get_all_translations_keys_and_values_translation_will_be_based_on_accept_language(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all translations keys and values. Translation will be based on accept language.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/translations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def overwrites_the_current_value_of_a_language_of_a_key_the_translation_will_be_applied_to_the_accept_language(
        self,
    ) -> CCVShopResult:
        """
        Overwrites the current value of a language of a key. The translation will be applied to the accept language.
        """
        return self.client._put(
            uri_path="/api/rest/v1/translations/",
        )