"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/usergroupstaggeredpriceadjustments/:id/ → Deleting an adjustment. Prices and discounts will be reverted to default for this user.
- GET /:version/usergroupstaggeredpriceadjustments/ → Get all adjustments. This can only be done by either usergroup_id, product_id, staggeredprice_id or a combination of them.
- GET /:version/usergroupstaggeredpriceadjustments/:id/ → Get one adjustment by id.
- OPTIONS /:version/usergroupstaggeredpriceadjustments/ → None
- PATCH /:version/usergroupstaggeredpriceadjustments/:id/ → Update an existing adjustment.
- POST /:version/usergroupstaggeredpriceadjustments/ → Create a new adjustment for an user for a product staggered price.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Usergroupstaggeredpriceadjustments(CCVApiEndpoints):
    """
    UserGroupStaggeredPriceAdjustments are adjusted product staggered prices for a specific usergroup. This feature is only available if B2B is enabled.
    """

    def deleting_an_adjustment_prices_and_discounts_will_be_reverted_to_default_for_this_user(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Deleting an adjustment. Prices and discounts will be reverted to default for this user.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/usergroupstaggeredpriceadjustments/{id}/",
        )

    def get_all_adjustments_this_can_only_be_done_by_either_usergroup_id,_product_id,_staggeredprice_id_or_a_combination_of_them(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all adjustments. This can only be done by either usergroup_id, product_id, staggeredprice_id or a combination of them.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/usergroupstaggeredpriceadjustments/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_adjustment_by_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one adjustment by id.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/usergroupstaggeredpriceadjustments/{id}/",
        )

    def update_an_existing_adjustment(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Update an existing adjustment.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/usergroupstaggeredpriceadjustments/{id}/",
            body=body,
        )

    def create_a_new_adjustment_for_an_user_for_a_product_staggered_price(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a new adjustment for an user for a product staggered price.
        """
        return self.client._post(
            uri_path="/api/rest/v1/usergroupstaggeredpriceadjustments/",
            body=body,
        )