"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/usergroupcategoryadjustments/:id/ → Deleting an adjustment. Prices and visibility will be reverted to default for this user group.
- GET /:version/usergroupcategoryadjustments/ → Get all adjustments. This can only be done by either usergroup_id or category_id or both.
- GET /:version/usergroupcategoryadjustments/:id/ → Get one adjustment by id.
- OPTIONS /:version/usergroupcategoryadjustments/ → None
- PATCH /:version/usergroupcategoryadjustments/:id/ → Update an existing adjustment.
- POST /:version/usergroupcategoryadjustments/ → Create a new adjustment for an user group.
"""

from typing import Any, List, Dict
from ..result import CCVShopResult
from .endpoint import CCVApiEndpoints

class Usergroupcategoryadjustments(CCVApiEndpoints):
    """
    UserGroupCategoryAdjustments are adjusted product prices or visibility for a specific user group. This feature is only available if B2B is enabled.
    """

    def deleting_an_adjustment_prices_and_visibility_will_be_reverted_to_default_for_this_user_group(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Deleting an adjustment. Prices and visibility will be reverted to default for this user group.
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/usergroupcategoryadjustments/{id}/",
        )

    def get_all_adjustments_this_can_only_be_done_by_either_usergroup_id_or_category_id_or_both(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all adjustments. This can only be done by either usergroup_id or category_id or both.
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/usergroupcategoryadjustments/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_adjustment_by_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one adjustment by id.
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/usergroupcategoryadjustments/{id}/",
        )

    def update_an_existing_adjustment(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Update an existing adjustment.
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/usergroupcategoryadjustments/{id}/",
            body=body,
        )

    def create_a_new_adjustment_for_an_user_group(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create a new adjustment for an user group.
        """
        return self.client._post(
            uri_path="/api/rest/v1/usergroupcategoryadjustments/",
            body=body,
        )