[project]
name = "ccvshop-client"
version = "0.1.0"
description = "Semi-generated CCVShop API client library"
dependencies = ["requests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
