"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/apicredentialdevicesettings/ → Retrieve all the settings for the related device based on api key
- PUT /:version/apicredentialdevicesettings/ → Overwrites all the settings related to the linked terminal device
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Apicredentialdevicesettings:
    def __init__(self, client: 'CCVClient'):
        """
        Settings that are linked to a terminal device.
        """
        self.client: 'CCVClient' = client

    def retrieve_all_the_settings_for_the_related_device_based_on_api_key(
        self,
    ) -> CCVShopResult:
        """
        Retrieve all the settings for the related device based on api key
        """
        return self.client._get(
            uri_path="/api/rest/v1/apicredentialdevicesettings/",
        )

    def overwrites_all_the_settings_related_to_the_linked_terminal_device(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Overwrites all the settings related to the linked terminal device
        """
        return self.client._put(
            uri_path="/api/rest/v1/apicredentialdevicesettings/",
            body=body,
        )