"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/apicredentialdevices/:id/ → Get a single terminal device
- POST /:version/apicredentialdevices/ → Store a new terminal device
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Apicredentialdevices:
    def __init__(self, client: 'CCVClient'):
        """
        A terminal device that's linked to a specific API credential.
        """
        self.client: 'CCVClient' = client

    def get_a_single_terminal_device(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get a single terminal device
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/apicredentialdevices/{id}/",
        )

    def store_a_new_terminal_device(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Store a new terminal device
        """
        return self.client._post(
            uri_path="/api/rest/v1/apicredentialdevices/",
            body=body,
        )