"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/apppsppaymethods/:id/ → Deletes a paymethod from the app psp
- GET /:version/apppsp/:id/apppsppaymethods/ → Gets all paymethods of this App Payment Service Provider
- GET /:version/apppsppaymethods/:id/ → Gets a single paymethod by resource id
- PATCH /:version/apppsppaymethods/:id/ → Patches a paymethod
- POST /:version/apppsp/:id/apppsppaymethods/ → Creates a new paymethod within the App Payment Service Provider
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Apppsppaymethods:
    def __init__(self, client: 'CCVClient'):
        """
        App PSP Paymethods are child resources of the App Payment Service Provider. These paymethods are available in the webshop's backend.
        """
        self.client: 'CCVClient' = client

    def deletes_a_paymethod_from_the_app_psp(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Deletes a paymethod from the app psp
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/apppsppaymethods/{id}/",
        )

    def gets_all_paymethods_of_this_app_payment_service_provider(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Gets all paymethods of this App Payment Service Provider
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/apppsp/{id}/apppsppaymethods/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def gets_a_single_paymethod_by_resource_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets a single paymethod by resource id
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/apppsppaymethods/{id}/",
        )

    def patches_a_paymethod(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patches a paymethod
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/apppsppaymethods/{id}/",
            body=body,
        )

    def creates_a_new_paymethod_within_the_app_payment_service_provider(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates a new paymethod within the App Payment Service Provider
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/apppsp/{id}/apppsppaymethods/",
            body=body,
        )