"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/basesubscriptions/ → Gives all base subscriptions (ie
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Basesubscriptions:
    def __init__(self, client: 'CCVClient'):
        """
        BaseSubscription are the foundation subscription of a webshop or SalesPOS.
        """
        self.client: 'CCVClient' = client

    def gives_all_base_subscriptions_(ie(
        self,
    ) -> CCVShopResult:
        """
        Gives all base subscriptions (ie
        """
        return self.client._get(
            uri_path="/api/rest/v1/basesubscriptions/",
        )