"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/categoryproductlayouts/:id/ → Get one layout for products in a category
- GET /:version/categoryproductlayouts/ → Get all layout for products in a category
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Categoryproductlayouts:
    def __init__(self, client: 'CCVClient'):
        """
        This is the lay-out of product within a category.
        """
        self.client: 'CCVClient' = client

    def get_one_layout_for_products_in_a_category(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one layout for products in a category
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/categoryproductlayouts/{id}/",
        )

    def get_all_layout_for_products_in_a_category(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all layout for products in a category
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/categoryproductlayouts/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )