"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/credentials/:id/ → Deletes current API credential
- GET /:version/credentials/ → Returns a collection of credentials
- GET /:version/credentials/:id/ → Returns the current API credential with the resource id
- POST /:version/webshops/:id/credentials/ → Creates a new set API credentials for the parent webshop
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Credentials:
    def __init__(self, client: 'CCVClient'):
        """
        Describes current API credential. Not all API credential can retrieve this. Contact CCV Shop if you are interessed in using this resource.
        """
        self.client: 'CCVClient' = client

    def deletes_current_api_credential(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Deletes current API credential
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/credentials/{id}/",
        )

    def returns_a_collection_of_credentials(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Returns a collection of credentials
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/credentials/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def returns_the_current_api_credential_with_the_resource_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Returns the current API credential with the resource id
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/credentials/{id}/",
        )

    def creates_a_new_set_api_credentials_for_the_parent_webshop(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates a new set API credentials for the parent webshop
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/webshops/{id}/credentials/",
            body=body,
        )