"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/users/:id/creditpointmutations/ → Gets the creditpoint mutation history of a user
- GET /:version/creditpointmutations/:id/ → Get one creditpoint mutation
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Creditpointmutations:
    def __init__(self, client: 'CCVClient'):
        """
        The creditpoint mutations of a user in the webshop.
        """
        self.client: 'CCVClient' = client

    def gets_the_creditpoint_mutation_history_of_a_user(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Gets the creditpoint mutation history of a user
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/users/{id}/creditpointmutations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_creditpoint_mutation(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one creditpoint mutation
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/creditpointmutations/{id}/",
        )