"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/users/:id/creditpoints/ → Gets a resource with creditpoints and a last mutation date
- PUT /:version/users/:id/creditpoints/ → Put the creditpoints of a user as is
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Creditpoints:
    def __init__(self, client: 'CCVClient'):
        """
        The creditpoint of a user in the webshop.
        """
        self.client: 'CCVClient' = client

    def gets_a_resource_with_creditpoints_and_a_last_mutation_date(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets a resource with creditpoints and a last mutation date
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/users/{id}/creditpoints/",
        )

    def put_the_creditpoints_of_a_user_as_is(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Put the creditpoints of a user as is
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/users/{id}/creditpoints/",
            body=body,
        )