"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/usergroups/:id/disabledpaymethods/ → Get all disabled paymethods for this user group
- GET /:version/users/:id/disabledpaymethods/ → Get all disabled paymethods for this user
- PUT /:version/usergroups/:id/disabledpaymethods/ → Change the disabled paymethods for an user group
- PUT /:version/users/:id/disabledpaymethods/ → Change the disabled paymethods for an user
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Disabledpaymethods:
    def __init__(self, client: 'CCVClient'):
        """
        Describes a disabled paymethod for a specific user or user group. This paymethod is hidden for the user or all users within a gropup during the checkout. See the resource /paymethods for available options.
        """
        self.client: 'CCVClient' = client

    def get_all_disabled_paymethods_for_this_user_group(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all disabled paymethods for this user group
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/usergroups/{id}/disabledpaymethods/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_all_disabled_paymethods_for_this_user(
        self,
        id: str,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all disabled paymethods for this user
        """
        return self.client._get_paged(
            uri_path=f"/api/rest/v1/users/{id}/disabledpaymethods/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def change_the_disabled_paymethods_for_an_user_group(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Change the disabled paymethods for an user group
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/usergroups/{id}/disabledpaymethods/",
            body=body,
        )

    def change_the_disabled_paymethods_for_an_user(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Change the disabled paymethods for an user
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/users/{id}/disabledpaymethods/",
            body=body,
        )