"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/webshops/:id/geozonecountries/ → Retrieve all countries of the webshop's geozones
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Geozonecountries:
    def __init__(self, client: 'CCVClient'):
        """
        This describes the geozone countries for a webshop.
        """
        self.client: 'CCVClient' = client

    def retrieve_all_countries_of_the_webshop's_geozones(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Retrieve all countries of the webshop's geozones
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/webshops/{id}/geozonecountries/",
        )