"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/invoices/ → Get all invoices of this webshop
- GET /:version/invoices/:id/ → Get one invoices by id
- PATCH /:version/invoices/:id/ → Patch an invoice
- POST /:version/orders/:id/invoices/ → Create an invoice for this order
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Invoices:
    def __init__(self, client: 'CCVClient'):
        """
        These are the invoices of a webshop But this could also be used to do a POST or only get one invoice.
        """
        self.client: 'CCVClient' = client

    def get_all_invoices_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all invoices of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/invoices/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_invoices_by_id(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one invoices by id
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/invoices/{id}/",
        )

    def patch_an_invoice(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch an invoice
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/invoices/{id}/",
            body=body,
        )

    def create_an_invoice_for_this_order(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Create an invoice for this order
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orders/{id}/invoices/",
            body=body,
        )