"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- DELETE /:version/orderrowattributevalues/:id/ → Delete an attribute value
- GET /:version/orderrowattributevalues/:id/ → Gets on value of an attribute
- POST /:version/orderrows/:id/orderrowattributevalues/ → Patch an attribute value
- PUT /:version/orderrows/:id/orderrowattributevalues/ → Patch an attribute value
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Orderrowattributevalues:
    def __init__(self, client: 'CCVClient'):
        """
        The value(s) of an attribute linked to an order row with an optional priceoffset. When ordering products with attributes (with additional prices) this resources gets filled (copied). To persist that data overtime.
        """
        self.client: 'CCVClient' = client

    def delete_an_attribute_value(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Delete an attribute value
        """
        return self.client._delete(
            uri_path=f"/api/rest/v1/orderrowattributevalues/{id}/",
        )

    def gets_on_value_of_an_attribute(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets on value of an attribute
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/orderrowattributevalues/{id}/",
        )

    def patch_an_attribute_value(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch an attribute value
        """
        return self.client._post(
            uri_path=f"/api/rest/v1/orderrows/{id}/orderrowattributevalues/",
            body=body,
        )

    def patch_an_attribute_value(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patch an attribute value
        """
        return self.client._put(
            uri_path=f"/api/rest/v1/orderrows/{id}/orderrowattributevalues/",
            body=body,
        )