"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/orderrowcalculator/:id/ → Get an orderrow calculator
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Orderrowcalculator:
    def __init__(self, client: 'CCVClient'):
        """
        Calculator values for an orderrow.
        """
        self.client: 'CCVClient' = client

    def get_an_orderrow_calculator(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get an orderrow calculator
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/orderrowcalculator/{id}/",
        )