"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/packages/:id/ → Get one package
- GET /:version/packages/ → Get all packages of this webshop
- PATCH /:version/packages/:id/ → Patches an existing product package
- POST /:version/packages/ → Creates a new product package
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Packages:
    def __init__(self, client: 'CCVClient'):
        """
        Each product has a package. Shipping costs are calculate based on the packages of the order. Multiple product with the same package will be combined when calculating.
        """
        self.client: 'CCVClient' = client

    def get_one_package(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one package
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/packages/{id}/",
        )

    def get_all_packages_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all packages of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/packages/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def patches_an_existing_product_package(
        self,
        id: str,
        body: Dict,
    ) -> CCVShopResult:
        """
        Patches an existing product package
        """
        return self.client._patch(
            uri_path=f"/api/rest/v1/packages/{id}/",
            body=body,
        )

    def creates_a_new_product_package(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Creates a new product package
        """
        return self.client._post(
            uri_path="/api/rest/v1/packages/",
            body=body,
        )