"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/quotations/ → Get all quotations of this webshop
- GET /:version/quotations/:id/ → Get one Quotation
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Quotations:
    def __init__(self, client: 'CCVClient'):
        """
        These are the quotations of a webshop.
        """
        self.client: 'CCVClient' = client

    def get_all_quotations_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all quotations of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/quotations/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_quotation(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one Quotation
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/quotations/{id}/",
        )