"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/returns/ → Get all returns of this webshop
- GET /:version/returns/:id/ → Get one return object
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Returns:
    def __init__(self, client: 'CCVClient'):
        """
        These are the returns of a webshop.
        """
        self.client: 'CCVClient' = client

    def get_all_returns_of_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all returns of this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/returns/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )

    def get_one_return_object(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one return object
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/returns/{id}/",
        )