"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/ → Get all available resources for this public key
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Root:
    def __init__(self, client: 'CCVClient'):
        """
        This is a collection of available resources for this Public Key.
        """
        self.client: 'CCVClient' = client

    def get_all_available_resources_for_this_public_key(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all available resources for this public key
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )