"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/servicecategories/:id/ → Gets one appstore categorie
- GET /:version/servicecategories/ → Gets all appsstore categories
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Servicecategories:
    def __init__(self, client: 'CCVClient'):
        """
        These are alle the services categories.
        """
        self.client: 'CCVClient' = client

    def gets_one_appstore_categorie(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Gets one appstore categorie
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/servicecategories/{id}/",
        )

    def gets_all_appsstore_categories(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Gets all appsstore categories
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/servicecategories/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )