"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- POST /:version/subscriptionupgrades/ → Post a subscription upgrade
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Subscriptionupgrades:
    def __init__(self, client: 'CCVClient'):
        """
        Can do an upgrade of the current SalesPOS subscription to a new subscription. For instance from sales_pos_trial to sales_pos.
        """
        self.client: 'CCVClient' = client

    def post_a_subscription_upgrade(
        self,
        body: Dict,
    ) -> CCVShopResult:
        """
        Post a subscription upgrade
        """
        return self.client._post(
            uri_path="/api/rest/v1/subscriptionupgrades/",
            body=body,
        )