"""
This file is auto-generated by the CCVShop API code generator.

⚠️ Do not edit manually – changes will be overwritten.
Endpoints:
- GET /:version/takeoutslots/:id/ → Get one slot
- GET /:version/takeoutslots/ → Get all slots for this webshop
"""

from typing import Dict
from ccv.result import CCVShopResult
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from ccv.client import CCVClient

class Takeoutslots:
    def __init__(self, client: 'CCVClient'):
        """
        Takeout slots for pickup or delivery.
        """
        self.client: 'CCVClient' = client

    def get_one_slot(
        self,
        id: str,
    ) -> CCVShopResult:
        """
        Get one slot
        """
        return self.client._get(
            uri_path=f"/api/rest/v1/takeoutslots/{id}/",
        )

    def get_all_slots_for_this_webshop(
        self,
        per_page: int = 100,
        total_pages: int = 1,
        **params,
    ) -> CCVShopResult:
        """
        Get all slots for this webshop
        """
        return self.client._get_paged(
            uri_path="/api/rest/v1/takeoutslots/",
            per_page=per_page,
            total_pages=total_pages,
            **params,
        )
