[project]
name = "ccv"
version = "0.2.0"
description = "Semi-generated CCVShop API client library"
dependencies = ["requests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
